/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.unknowjava;

import java.util.Collections;
import java.util.Stack;
import java.util.stream.Collectors;

public class App {
    static Stack<String> methodStack = new Stack<>();
    static String stackInfo = "";


    public String getGreeting() {
        stackInfo = stackInfo + "start to set getGreeting "+ methodStack.size() + "\n" ;
        methodStack.push("getGreeting");

        String result = "Hello World!";
        stackInfo = stackInfo + Collections.nCopies(methodStack.size(), "    ").stream().collect(Collectors.joining()) + methodStack.pop() + "\n";
        return result;
    }
    public String getGreeting2() {
        stackInfo = stackInfo + "start to set getGreeting2"+ methodStack.size() + "\n";
        methodStack.push("getGreeting2");
        String result =  "Hello World!" + getGreeting();
        getGreeting();
        getGreeting();
        stackInfo = stackInfo + Collections.nCopies(methodStack.size(), "    ").stream().collect(Collectors.joining()) + methodStack.pop() + "\n";
        return result;
    }


    public static void main(String[] args) {
        System.out.println(new App().getGreeting2());
        System.out.println(stackInfo);
    }
}
